using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MAPZ_lab_RPG.Entities.Items;

namespace MAPZ_lab_RPG.Entities.Shop
{
    public enum ItemNames
    {
        HealthRune = 1,
        DamageRune = 2,
        ArmorRune = 3
    }

    public class Shop
    {
        private static readonly Shop _instance = new Shop();
        private readonly ItemManager item_manager;

        public static Shop Instance
        {
            get { return _instance; }
        }

        private Shop()
        {
            item_manager = ItemManager.Instance;
        }
        public IItem BuyItem(string itemName, ref int heroBalance)
        {
            //TODO check if item is generated by GenerateItems and remove from list
            if (heroBalance >= 50){
                try
                {
                    IItem item = item_manager.CreateItem(itemName);
                    heroBalance -= 50;
                    return item;
                }
                catch (ArgumentException exc)
                {
                    System.Console.Out.WriteLine(exc);
                    throw;
                }
            }
            return null;
        }
        public List<IItem> GenerateItems()
        {
            List<int> randomList = new List<int>();
            Random rand = new Random();
            int itemCount = 4;
            for (int i = 0; i < itemCount; i++)
            {
                int choice = rand.Next(1,4);
                randomList.Add(choice);
            }
            
            List<IItem> itemList = new List<IItem>();
            foreach (var choice in randomList)
            {
                string itemName = ((ItemNames)choice).ToString();
                itemList.Add(item_manager.CreateItem(itemName));
            }
            return itemList;
        }
    }
}